variables:

  # Valores de recursos de Azure por crear o modificar el nombre si es que ya existen
  ml_workspace_connection: 'aml-workspace-base-connection'
  ml_aks_cluster: 'aks-base-cluster'
  ml_workspace_name: 'ml-workspace-base'
  ml_workspace_rg: 'mlops-practica'
  ml_compute_name: 'cpu-cluster'

  # Valores fijos
  ml_model_name: 'german-credit-basic-model'
  ml_model_path: 'models/german-credit-basic'
  ml_model_filename: 'credit-prediction.pkl'
  ml_experiment_name: 'german-credit-basic-ci'
  ml_deployment_name: 'german-credit-deployment'